### ISSUE TITLE
Adhoc adjustments (not the standard formula)

### ISSUE THREAD

**Issue by winterstein** [winterstein/sogive-app#20]
Adhoc adjustments not working - Against Malaria Foundation	Cost per beneficiary should be adhoc adjusted to £4.11 (this is because the derived figure reflects a too-low amount of overheads given the fast-growing nature of the organisation) Adhoc adjustments not working - Give Directly	Should see something like "£10 will fund £9.10 sent directly to someone in poverty"

**Comment by SanjayLikesCharities** [comment]
Further examples include Women for Women international (should be adhoc adjusted to equal the previous year's figure) and Project Mala (seems to be coming through correctly right from the start, which is interesting)

**Comment by SanjayLikesCharities** [comment]
Also need to consider how handle the inputs section of the charity page. E.g. where an adhoc adjustment is used, we might just not bother filling in the inputs since they might not be needed

**Comment by SanjayLikesCharities** [comment]
Solution: add in a column which indicates whether ot not here is an adhoc adj by pipulating the column with an eplanation of the adj (if here is an adj) and blank otherwise

**Comment by winterstein** [comment]
1. Sanjay to add the adjustment-explanation column and let me know a couple of examples.
2. Then Dan W to wire this up in the data-import and display.

**Comment by SanjayLikesCharities** [comment]
Have added in an extra column to explain adhoc adjustments - currently column AN in the spreadsheet. Where no adhoc adjustment is required, this column is left blank. It has been populated in a few cases, but I have not yet gone through and checked all the charities to ensure that every instance of an adhoc adjustment has been recognised in that column.

**Comment by winterstein** [comment]
Done, but buggy: http://local.sogive.org/#charity?charityId=against-malaria-foundation

**Comment by winterstein** [comment]
OK - I've put in code for this. Re. Against Malaria Foundation - the system is using the 1st output, which doesn't have a custom cost-per-beneficiary, so the change isn't visible.

**Comment by SanjayLikesCharities** [comment]
Have just tried to test this. 
- AMF: I agree, no adhoc adjustment is applied, and one should be
Some more:
- Pardada Pardadi - also not coming through
- Bees for Development - also not coming through
- Project Mala - interestingly this one is correct and always has been. Is this because of rounding?
- SCI - using the calculated number, not the correct number

**Comment by SanjayLikesCharities** [comment]
I might be misunderstanding the comment "the system is using the 1st output, which doesn't have a custom cost-per-beneficiary", but it might be useful to note that for some of these charities (e.g. SCI) the spreadsheet only has one row, and that one row indicates that an adjustment is required

**Comment by winterstein** [comment]
Hello Sanjay

Hm... Bees for Development doesn't have any outputs defined.
http://app.sogive.org/#charity?charityId=bees-for-development

There's a comment in the spreadsheet about 17,250 households, but it's not
in the outputs column.

The way the code works:
It's looking for an output (preferably with a "unit") first, and then it
looks for a cost-per-beneficiary adjustment. If there's no output, then the
cost-per-ben isn't picked up.

 - Daniel

**Comment by SanjayLikesCharities** [comment]
This approach for how the code works isn't quite right. Maybe I was wrong to use the language "adhoc adjustment", which could be the reason for this confusion - perhaps "adhoc overwrite" or something would be better. Here's an explanation:
- one scenario is that we already have a cost per output, but we don't believe it, and we adjust it to get to something we believe more (the approach described would work fine in this scenario)
- another is that the standard calc method doesn't work because we don't have the required inputs, however the end result of the calc is available from the charity, in which case we simply use that. (the approach described would fail in this scenario - as you observed with the Bees for Dev example)
Also, when you said that this is the way the code works, did you mean that this is the way the code is intended to work? It doesn't seem to be working that way for AMF or SCI.

**Comment by winterstein** [comment]
A dummy number will drive an override.
